spring.application.name=household-budget-app
spring.datasource.url=jdbc:postgresql://localhost:5432/household-budget-app
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none